[package]
name = "adversary"
version = "0.1.0"
authors = ["Isaac Chen"]
description = "Adversarial property-based testing for Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ijchen/adversary"
documentation = "https://docs.rs/adversary"
edition = "2021"
include = ["/src/", "/Cargo.toml", "/README.md", "/LICENSE-*"]
publish = false

[dependencies]
rand = "0.8.5"

[dev-dependencies]
