[package]
name = "adversary"
version = "0.1.0"
authors = ["Isaac Chen"]
description = "Adversarial property-based testing for Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ijchen/adversary"
documentation = "https://docs.rs/adversary"
edition = "2024"
include = ["/src/", "/Cargo.toml", "/README.md", "/LICENSE-*"]
publish = false

[lints]
workspace = true

[dependencies]
rand = "0.8.5"
adversary-macros = { version = "0.1.0", path = "../adversary-macros", optional = true }
paste = "1.0.15"

[dev-dependencies]

[features]
default = ["macros"]
macros = ["dep:adversary-macros"]
