use crate::{rand::Rng, shrinker::Shrinker};

pub trait InputGenerator {
    /// The type generated by this generator, and given as input to the code
    /// being tested.
    type Input;

    // TODO(ichen): default this to Self::Input when associated type defaults
    // are stabilized (https://github.com/rust-lang/rust/issues/29661)
    // TODO: explain this
    type InputSource: Clone;

    /// Returns the number of possible values of type [`Input`], or [`None`] if
    /// that value is unknown or greater than [`usize::MAX`].
    ///
    /// [`Input`]: InputGenerator::Input
    fn cardinality(&self) -> Option<usize>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Returns an iterator over all possible values of type [`Input`], if
    /// possible.
    ///
    /// If [`cardinality`] returns [`None`], the contents of the iterator may be
    /// anything and should not be relied on. If [`cardinality`] returns
    /// [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`cardinality`] returns [`Some`], the returned
    /// iterator should yield every possible value of type [`Input`] exactly
    /// once, and always in the same order.
    ///
    /// [`Input`]: InputGenerator::Input
    /// [`cardinality`]: InputGenerator::cardinality
    fn exhaustive(&self) -> impl Iterator<Item = Self::InputSource>;

    /// Returns the number of adversarial inputs that will be returned by
    /// [`adversarial`], or [`None`] if that value is greater than
    /// [`usize::MAX`] or otherwise should not be relied on.
    ///
    /// [`adversarial`]: InputGenerator::adversarial
    fn adversarial_count(&self) -> Option<usize>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Returns an iterator over specifically-chosen adversarial inputs, if
    /// possible. These inputs are ones likely to encounter different branches
    /// or edge cases in the code being tested.
    ///
    /// If [`adversarial_count`] returns [`None`], the contents of the iterator
    /// may be anything and should not be relied on. If [`adversarial_count`]
    /// returns [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`adversarial_count`] returns [`Some`], the
    /// returned iterator should each adversarial value exactly once, and always
    /// in the same order.
    ///
    /// [`adversarial_count`]: InputGenerator::adversarial_count
    fn adversarial(&self) -> impl Iterator<Item = Self::InputSource>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Samples a random value of type [`Input`].
    ///
    /// The values are not necessarily sampled with equal distribution - some
    /// implementations may choose to return certain values more often than
    /// others, or may even have some values which will never be returned.
    ///
    /// This function should be deterministic when given the same rng in the
    /// same state - that is, if called multiple times with an `rng` that gives
    /// the same outputs, this function should return the same value.
    ///
    /// [`Input`]: InputGenerator::Input
    fn sample(&self, rng: &mut (impl Rng + ?Sized)) -> Self::InputSource;

    // TODO: docs outdated
    /// Returns a new [`Shrinker`], ready to be used for the shrinking process.
    ///
    /// The `failing_input` argument should be the initial failing input to be
    /// shrunk.
    ///
    /// [`Shrinker`]: InputGenerator::Shrinker
    fn new_shrinker(
        &self,
        failing_input: Self::InputSource,
    ) -> impl Shrinker<InputSource = Self::InputSource>;

    // TODO: docs
    // TODO: should this take an `InputSource` or an `&InputSource`?
    fn create_input(&self, input_source: Self::InputSource) -> Self::Input;
}
