use crate::{rand::Rng, shrinker::Shrinker};

pub trait ValueGen {
    /// The type generated by this generator, and given as input to the code
    /// being tested.
    type Value;

    // TODO(ichen): default this to Self::Value when associated type defaults
    // are stabilized (https://github.com/rust-lang/rust/issues/29661)
    // TODO: explain this
    type Seed: Clone;

    /// Returns the number of possible values of type [`Value`], or [`None`] if
    /// that value is unknown or greater than [`usize::MAX`].
    ///
    /// [`Value`]: ValueGen::Value
    fn cardinality(&self) -> Option<usize>;

    // TODO: docs outdated because Seed was added
    /// Returns an iterator over all possible values of type [`Value`], if
    /// possible.
    ///
    /// If [`cardinality`] returns [`None`], the contents of the iterator may be
    /// anything and should not be relied on. If [`cardinality`] returns
    /// [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`cardinality`] returns [`Some`], the returned
    /// iterator should yield every possible value of type [`Value`] exactly
    /// once, and always in the same order.
    ///
    /// [`Value`]: ValueGen::Value
    /// [`cardinality`]: ValueGen::cardinality
    fn exhaustive(&self) -> impl Iterator<Item = Self::Seed>;

    /// Returns the number of adversarial values that will be returned by
    /// [`adversarial`], or [`None`] if that value is greater than
    /// [`usize::MAX`] or otherwise should not be relied on.
    ///
    /// [`adversarial`]: ValueGen::adversarial
    fn adversarial_count(&self) -> Option<usize>;

    // TODO: docs outdated because Seed was added
    /// Returns an iterator over specifically-chosen adversarial values, if
    /// possible. These values are ones likely to encounter different branches
    /// or edge cases in the code being tested.
    ///
    /// If [`adversarial_count`] returns [`None`], the contents of the iterator
    /// may be anything and should not be relied on. If [`adversarial_count`]
    /// returns [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`adversarial_count`] returns [`Some`], the
    /// returned iterator should each adversarial value exactly once, and always
    /// in the same order.
    ///
    /// [`adversarial_count`]: ValueGen::adversarial_count
    fn adversarial(&self) -> impl Iterator<Item = Self::Seed>;

    // TODO: docs outdated because Seed was added
    /// Samples a random value of type [`Value`].
    ///
    /// The values are not necessarily sampled with equal distribution - some
    /// implementations may choose to return certain values more often than
    /// others, or may even have some values which will never be returned.
    ///
    /// This function should be deterministic when given the same rng in the
    /// same state - that is, if called multiple times with an `rng` that gives
    /// the same outputs, this function should return the same value.
    ///
    /// [`Value`]: ValueGen::Value
    fn sample(&self, rng: &mut (impl Rng + ?Sized)) -> Self::Seed;

    // TODO: docs outdated
    /// Returns a new [`Shrinker`], ready to be used for the shrinking process.
    ///
    /// The `failing_value_seed` argument should be the seed of the initial
    /// failing value to be shrunk.
    ///
    /// [`Shrinker`]: ValueGen::Shrinker
    fn new_shrinker(&self, failing_value_seed: Self::Seed) -> impl Shrinker<Seed = Self::Seed>;

    // TODO: docs
    // TODO: should this take a `Seed` or a `&Seed`?
    fn create_value(&self, seed: Self::Seed) -> Self::Value;
}
