use crate::{rand::Rng, shrinker::Shrinker};

fn test<G: ValueGen + ?Sized>(g: Box<G>, failing_value_seed: G::Seed) -> G::Shrinker {
    g.new_shrinker(failing_value_seed)
}

pub trait ValueGen {
    /// The type generated by this generator, and given as input to the code
    /// being tested.
    type Value;

    // TODO(ichen): default this to Self::Value when associated type defaults
    // are stabilized (https://github.com/rust-lang/rust/issues/29661)
    /// A "seed" that can be given to this [`ValueGen`] to create a [`Value`].
    ///
    /// [`Value`]: ValueGen::Value
    type Seed: Clone;

    /// The [`Shrinker`] type returned by [`new_shrinker`].
    ///
    /// [`new_shrinker`]: ValueGen::new_shrinker
    type Shrinker: Shrinker<Self> + 'static;

    /// Returns the length of the iterator returned by [`exhaustive`], or
    /// [`None`] if that length is greater than [`usize::MAX`] or otherwise
    /// should not be relied on.
    ///
    /// [`exhaustive`]: ValueGen::exhaustive
    fn cardinality(&self) -> Option<usize>;

    /// Returns an iterator over [`Seed`]s for all possible values that could be
    /// generated by this [`ValueGen`], if possible.
    ///
    /// If [`cardinality`] returns [`None`], the contents of the iterator may be
    /// anything and should not be relied on. If [`cardinality`] returns
    /// [`Some`], the returned iterator must yield exactly that many items.
    ///
    /// Additionally, assuming [`cardinality`] returns [`Some`], the iterator
    /// returned by this function must always yield the same items in the same
    /// order.
    ///
    /// [`Seed`]: ValueGen::Seed
    /// [`cardinality`]: ValueGen::cardinality
    fn exhaustive(&self) -> impl Iterator<Item = Self::Seed>;

    /// Returns the length of the iterator returned by [`adversarial`], or
    /// [`None`] if that length is greater than [`usize::MAX`] or otherwise
    /// should not be relied on.
    ///
    /// [`adversarial`]: ValueGen::adversarial
    fn adversarial_count(&self) -> Option<usize>;

    /// Returns an iterator over [`Seed`]s for specifically chosen adversarial
    /// values, if possible. These values are ones likely to encounter different
    /// branches or edge cases in the code being tested.
    ///
    /// If [`adversarial_count`] returns [`None`], the contents of the iterator
    /// may be anything and should not be relied on. If [`adversarial_count`]
    /// returns [`Some`], the returned iterator must yield exactly that many
    /// items.
    ///
    /// Additionally, assuming [`adversarial_count`] returns [`Some`], the
    /// iterator returned by this function must always yield the same items in
    /// the same order.
    ///
    /// [`Seed`]: ValueGen::Seed
    /// [`adversarial_count`]: ValueGen::adversarial_count
    fn adversarial(&self) -> impl Iterator<Item = Self::Seed>;

    /// Samples the [`Seed`] of a random value.
    ///
    /// The values are not necessarily sampled with equal distribution - some
    /// implementations may choose to return certain values more often than
    /// others, or may even have some values which will never be returned.
    ///
    /// This function should be deterministic when given the same rng in the
    /// same state - that is, if called multiple times with an `rng` that gives
    /// the same outputs, this function should return the same value.
    ///
    /// [`Seed`]: ValueGen::Seed
    fn sample(&self, rng: &mut (impl Rng + ?Sized)) -> Self::Seed;

    /// Returns a new [`Shrinker`], ready to be used for the shrinking process.
    ///
    /// The `failing_value_seed` argument should be the seed of the initial
    /// failing value to be shrunk.
    fn new_shrinker(&self, failing_value_seed: Self::Seed) -> Self::Shrinker;

    // TODO: should this take a `Seed` or a `&Seed`?
    /// Create a [`Value`] from a [`Seed`].
    ///
    /// [`Value`]: ValueGen::Value
    /// [`Seed`]: ValueGen::Seed
    fn create_value(&self, seed: Self::Seed) -> Self::Value;
}
