use crate::{rand::Rng, report::Observation};

// TODO(ichen): I believe this T is always (A, B) - consider restructuring this
// struct to just be generic over two things instead
pub enum NextAttempt<T, S> {
    Done,
    InfoGathering(InputWithShrinkable<T, S>),
    ShrinkAttempt(InputWithShrinkable<T, S>),
}

pub struct InputWithShrinkable<T, S>(pub T, pub S);

pub trait InputGenerator {
    /// The type generated by this generator, and given as input to the code
    /// being tested.
    type Input;

    // TODO(ichen): default this to Self::Input when associated type defaults
    // are stabilized (https://github.com/rust-lang/rust/issues/29661)
    // TODO: explain this
    type ShrinkableInput;

    /// A type that stores shrinking history with the necessary information to
    /// determine the next value to try during shrinking, when to stop
    /// attempting to shrink, and information to generate a report of what
    /// happened during shrinking.
    type History;

    /// Returns the number of possible values of type [`Input`], or [`None`] if
    /// that value is unknown or greater than [`usize::MAX`].
    ///
    /// [`Input`]: NewInputGenerator::Input
    fn cardinality(&self) -> Option<usize>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Returns an iterator over all possible values of type [`Input`], if
    /// possible.
    ///
    /// If [`cardinality`] returns [`None`], the contents of the iterator may be
    /// anything and should not be relied on. If [`cardinality`] returns
    /// [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`cardinality`] returns [`Some`], the returned
    /// iterator should yield every possible value of type [`Input`] exactly
    /// once, and always in the same order.
    ///
    /// [`Input`]: NewInputGenerator::Input
    /// [`cardinality`]: NewInputGenerator::cardinality
    fn exhaustive(
        &self,
    ) -> impl Iterator<Item = InputWithShrinkable<Self::Input, Self::ShrinkableInput>>;

    /// Returns the number of adversarial inputs that will be returned by
    /// [`adversarial`], or [`None`] if that value is greater than
    /// [`usize::MAX`] or otherwise should not be relied on.
    ///
    /// [`adversarial`]: NewInputGenerator::adversarial
    fn adversarial_count(&self) -> Option<usize>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Returns an iterator over specifically-chosen adversarial inputs, if
    /// possible. These inputs are ones likely to encounter different branches
    /// or edge cases in the code being tested.
    ///
    /// If [`adversarial_count`] returns [`None`], the contents of the iterator
    /// may be anything and should not be relied on. If [`adversarial_count`]
    /// returns [`Some`], the iterator should yield exactly that many items.
    ///
    /// Additionally, assuming [`adversarial_count`] returns [`Some`], the
    /// returned iterator should each adversarial value exactly once, and always
    /// in the same order.
    ///
    /// [`adversarial_count`]: NewInputGenerator::adversarial_count
    fn adversarial(
        &self,
    ) -> impl Iterator<Item = InputWithShrinkable<Self::Input, Self::ShrinkableInput>>;

    // TODO: docs outdated because ShrinkableInput was added
    /// Samples a random value of type [`Input`].
    ///
    /// The values are not necessarily sampled with equal distribution - some
    /// implementations may choose to return certain values more often than
    /// others, or may even have some values which will never be returned.
    ///
    /// This function should be deterministic when given the same rng in the
    /// same state - that is, if called multiple times with an `rng` that gives
    /// the same outputs, this function should return the same value.
    ///
    /// [`Input`]: NewInputGenerator::Input
    fn sample(
        &self,
        rng: &mut (impl Rng + ?Sized),
    ) -> InputWithShrinkable<Self::Input, Self::ShrinkableInput>;

    /// Returns a new, "blank slate" [`History`], ready to be used for the
    /// shrinking process.
    ///
    /// [`History`]: NewInputGenerator::History
    fn new_history(&self) -> Self::History;

    /// TODO
    fn next_input(
        &self,
        rng: &mut impl Rng,
        history: &Self::History,
    ) -> NextAttempt<Self::Input, Self::ShrinkableInput>;

    /// TODO
    fn update_history(
        &self,
        history: &mut Self::History,
        shrinkable_input: Self::ShrinkableInput,
        test_passed: bool,
    );

    /// TODO
    fn generate_observations(&self, history: Self::History) -> Vec<Observation>;
}
